# Python & numpy review

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(3,)

In [5]:
# numpy 특징 : n차원의 객체(ndarray)

* List 와 indexing

In [6]:
A = [1, 'b', 'c']

In [7]:
B = [10,20,30,40,50,60]

In [8]:
B[3:6]

[40, 50, 60]

In [9]:
Blist = B[3:6]
Blist

[40, 50, 60]

In [10]:
B[3:6][1]

50

In [11]:
type(B[3:6])

list

* List in List

In [12]:
B = [1, 2, 'c', [1, 3, 4]]
B

[1, 2, 'c', [1, 3, 4]]

In [13]:
B[3][1]

3

In [14]:
type(B[3])

list

In [15]:
C = [[1,2,3,4], [3, [12, 4, 5, 65], 'c', 10], 'a']

In [16]:
C[1]

[3, [12, 4, 5, 65], 'c', 10]

In [17]:
C[1][1]

[12, 4, 5, 65]

In [18]:
C[1][1][3]

65

In [19]:
C[1][1][3] + 10

75

### Vector의 표기 단위 차이

In [20]:
X = np.array([[5, 6, 8], [6, 7, 4]])
X

array([[5, 6, 8],
       [6, 7, 4]])

In [21]:
xr1 = np.array([5,6,7])
xr1

array([5, 6, 7])

In [22]:
# ndim : 배열의 차원을 알 수 있다. 배열의 차원을 쉽게 알기 위해서는 대괄호의 한쪽 갯수를 세면 쉬움

In [23]:
xr1.ndim

1

In [24]:
XR1 = np.array([[5,6,7]])
XR1

array([[5, 6, 7]])

In [25]:
XR1.ndim

2

In [26]:
X1 = np.array([[5], [6]])
X1

array([[5],
       [6]])

In [27]:
X1.ndim

2

In [28]:
a = np.array([12,3,4])

In [29]:
b = np.array([[12,3,4]])

In [30]:
a.ndim # 괄호 겹수에 따라서 달라짐

1

In [31]:
b.ndim

2

In [32]:
X.ndim

2

In [33]:
X.dtype

dtype('int32')

In [34]:
type(X)

numpy.ndarray

In [35]:
X = np.array([[1],[2],[3]])

In [36]:
X

array([[1],
       [2],
       [3]])

In [37]:
X.shape

(3, 1)

In [38]:
X = np.array([[1., 2., 3.], 
              [4., 5., 6.,]])
X

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
X.shape

(2, 3)

In [40]:
X.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [41]:
X.reshape(3, 2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [42]:
X.reshape(1, 6)

array([[1., 2., 3., 4., 5., 6.]])

In [43]:
X.reshape(1, -1)

array([[1., 2., 3., 4., 5., 6.]])

In [44]:
X.reshape(6, 1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [45]:
X.reshape(-1, 1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [46]:
A = X.reshape(6, 1)
A

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [47]:
X

array([[1., 2., 3.],
       [4., 5., 6.]])

In [48]:
a = np.array([1,2,3])

In [49]:
a.T

array([1, 2, 3])

In [50]:
b = np.array([[1,2,3]])

In [51]:
b.T

array([[1],
       [2],
       [3]])

In [52]:
x1 = np.array([[5], [6], [8]])
x2 = np.array([[6], [7], [5]])
print('x1 = ', x1)
print('x2 = ', x2)

x1 =  [[5]
 [6]
 [8]]
x2 =  [[6]
 [7]
 [5]]


In [53]:
x2.shape

(3, 1)

In [54]:
x1T = x1.T
x2T = x2.T
print('x1T = ', x1T)
print('x2T = ', x2T)

x1T =  [[5 6 8]]
x2T =  [[6 7 5]]


In [55]:
x1TT = x1.reshape(1, 3)
x2TT = x2.reshape(1, 3)
print('x1TT = ', x1TT)
print('x2TT = ', x2TT)

x1TT =  [[5 6 8]]
x2TT =  [[6 7 5]]


* `vstack` (vertical (수직) stack (쌓다))

In [56]:
X = np.vstack([x1T, x2T])
X

array([[5, 6, 8],
       [6, 7, 5]])

* `hstack` (horizontal (수평) stack (쌓다))

In [57]:
Xhstack = np.hstack([x1T, x2T])
Xhstack

array([[5, 6, 8, 6, 7, 5]])

In [58]:
Xhstack2 = np.hstack([x1, x2])
Xhstack2

array([[5, 6],
       [6, 7],
       [8, 5]])

In [59]:
# ones : 1로 이루어진 배열을 만든다 , 안에 넣어줄 때 튜플 형태로 넣어주여야 된다

In [60]:
onevec = np.ones((2, 3)) # 차원을 튜플로 1차원 이상인 경우
onevec

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
# zeros : 0로 이루어진 배열을 만든다.

In [62]:
zerovec = np.zeros((2, 3)) # 차원을 튜플로 1차원 이상인 경우
zerovec

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.arange(0, 10) # 이상, 미만

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
for i in np.arange(3):
    print(i)

0
1
2


In [65]:
np.linspace(0, 3, 10) # 0부터 3까지인데 10개로 동일하게 만들어라

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [66]:
d = 2*np.random.rand(1, 10)-1
d

array([[-0.60660489,  0.25613894, -0.75104661, -0.05702911, -0.9974944 ,
        -0.28399474, -0.12954909,  0.39791819,  0.62303012, -0.59118303]])

In [67]:
e = np.random.randn(3, 4)
e

array([[-0.6512482 , -2.10545221, -0.15490118,  2.56003169],
       [-0.98843124, -1.81478744, -0.51187616,  1.31176601],
       [ 0.83115987,  1.87978079, -0.63188339,  0.43251085]])

* squeeze() 차원축소

In [68]:
f = np.array([[[1,2,3,4]]])
f

array([[[1, 2, 3, 4]]])

In [69]:
f.ndim

3

In [70]:
f.shape

(1, 1, 4)

In [71]:
f.squeeze().ndim

1

In [72]:
f.squeeze().shape

(4,)

* Matrix multiplication

In [73]:
A = np.arange(0, 6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [74]:
A.shape

(3, 2)

In [75]:
B = np.random.randn(3,4)
B

array([[ 0.96387273, -0.45884421, -0.9108605 , -0.66410048],
       [-0.38041406, -1.54127608,  0.25686257, -0.37748425],
       [-0.56006241,  0.37672975, -0.269652  , -0.15131858]])

In [76]:
B.shape

(3, 4)

In [77]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [78]:
A[0,1]

1

In [79]:
A[1][1]

3

In [80]:
A[2,1]

5

In [81]:
a1 = A[:,0].reshape(-1, 1)
a1

array([[0],
       [2],
       [4]])

In [82]:
B

array([[ 0.96387273, -0.45884421, -0.9108605 , -0.66410048],
       [-0.38041406, -1.54127608,  0.25686257, -0.37748425],
       [-0.56006241,  0.37672975, -0.269652  , -0.15131858]])

In [83]:
b2 = B[:, 1].reshape(-1, 1)
b2

array([[-0.45884421],
       [-1.54127608],
       [ 0.37672975]])

In [84]:
C = np.matmul(a1.T, b2)
print(C)
print(C[0][0])

[[-1.57563316]]
-1.5756331617454953


In [85]:
C.shape

(1, 1)

In [88]:
a = np.linspace(0, 6, 4).reshape(1, 4)
a

array([[0., 2., 4., 6.]])

In [89]:
b = np.ones((4, 1))
b

array([[1.],
       [1.],
       [1.],
       [1.]])

In [90]:
np.matmul(a, b)[0][0]

12.0

In [91]:
D = np.random.randn(3, 3)
D

array([[ 1.68978153,  0.26483551,  0.39918799],
       [-0.89456198, -1.1941568 , -1.4584722 ],
       [ 0.7684463 , -1.88311373,  0.16195697]])

In [92]:
E = np.random.randn(3, 3)
E

array([[-0.71061647, -2.15337594,  1.68388189],
       [-1.84854273,  0.10681976, -0.79101231],
       [-0.04535811, -0.00813372,  1.39735071]])

In [93]:
D + E

array([[ 0.97916506, -1.88854043,  2.08306987],
       [-2.74310471, -1.08733705, -2.2494845 ],
       [ 0.72308819, -1.89124746,  1.55930768]])

In [94]:
D - E

array([[ 2.40039801,  2.41821144, -1.2846939 ],
       [ 0.95398076, -1.30097656, -0.66745989],
       [ 0.8138044 , -1.87498001, -1.23539374]])

In [95]:
c1 = D[0,:]
d1 = E[0,:]

In [96]:
c1 + d1

array([ 0.97916506, -1.88854043,  2.08306987])

In [97]:
a = np.array([1,2,3,4])
b = 2*np.ones(4)
b

array([2., 2., 2., 2.])

In [98]:
a

array([1, 2, 3, 4])

In [99]:
c = a*b # 행렬곱이 일어나지 않음 행렬곱은 matmul matmul과는 다른 연산
c

array([2., 4., 6., 8.])

In [100]:
np.sum(a*b)

20.0

In [101]:
np.matmul(a, b.reshape(-1, 1))

array([20.])

In [102]:
A = np.arange(3, 11, 1).reshape(2, 4)
A

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [103]:
np.sum(A)

52

In [104]:
np.sum(A, axis = 0) # 수직으로 더 함

array([10, 12, 14, 16])

In [105]:
np.sum(A, axis = 1) # 수평으로 더 함

array([18, 34])

In [106]:
c = np.sum(A, axis = 1).reshape(-1, 1)
c

array([[18],
       [34]])

* Broadcast

In [107]:
A = np.random.randn(4, 3)
A

array([[-0.04519905,  0.52392939, -0.71528933],
       [-0.60927553, -1.0221541 ,  1.50100302],
       [-0.72464996, -0.19480749, -1.94619019],
       [ 0.46563585,  1.91891415,  1.05111344]])

In [108]:
B = np.ones((4, 1))
B

array([[1.],
       [1.],
       [1.],
       [1.]])

In [109]:
A + B

array([[ 0.95480095,  1.52392939,  0.28471067],
       [ 0.39072447, -0.0221541 ,  2.50100302],
       [ 0.27535004,  0.80519251, -0.94619019],
       [ 1.46563585,  2.91891415,  2.05111344]])

In [ ]:
############### 다시 처음부터 정리해보기 ###############
############### 나중에 이것 저것 써 보면서 어떻게 돌아가는 건지 알아보면 좋을듯 ###############

In [ ]:
# array : 배열
# ndim : 배열의 차원을 알 수 있다. 배열의 차원을 쉽게 알기 위해서는 대괄호의 한쪽 갯수를 세면 쉬움
# random.randn : 난수를 생성함 ex : np.random.randn(3, 3)
# linspace : 균일한 숫자 간격으로 나눔 ex : np.linspace(시작, 끝, 일정하게 나눌 크기)
# arange : 수열을 만들기 위해서 사용함 ex : np.arange(시작, 미만, step 크기)
# ones : 1로 채워진 배열을 만들어줌(튜플 형태로 넣어줘야 된다.) ex : np.ones((2,3))
# zeros : 0으로 채워진 배열을 만들어줌(튜플 형태로 넣어줘야 된다.) ex : np.zeros((2,3))
# shape : 차원을 나타냄
# reshape : 차원의 형태를 바꿔줌
# matmul : 배열의 행렬곱
# dot : 곱함
# @ : 곱함
# matmul, dot의 차이점을 정확히는 모르겠는데, 2차원 행렬의 곱셈에서는 같은 기능을 수행하고 고차원으로 가면 기능이 다름
# sum : 더함
# vstack : 수직으로 쌓음
# hstack : 수평으로 쌓음
# squeeze : 차원을 1로 만들어줌 ex : [[1,2,3,4]] ---> [1,2,3,4]