# Python & numpy review

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

* List 와 indexing

In [3]:
A = [1, 'b', 'c']

In [4]:
B = [10,20,30,40,50,60]

In [5]:
B[3:6]

[40, 50, 60]

In [6]:
Blist = B[3:6]
Blist

[40, 50, 60]

In [7]:
B[3:6][1]

50

In [8]:
type(B[3:6])

list

* List in List

In [9]:
B = [1, 2, 'c', [1, 3, 4]]
B

[1, 2, 'c', [1, 3, 4]]

In [10]:
B[3][1]

3

In [11]:
type(B[3])

list

In [12]:
C = [[1,2,3,4], [3, [12, 4, 5, 65], 'c', 10], 'a']

In [13]:
C[1][1][3] + 10

75

### Vector의 표기 단위 차이

In [14]:
X = np.array([[5, 6, 8], [6, 7, 4]])
X

array([[5, 6, 8],
       [6, 7, 4]])

In [15]:
xr1 = np.array([5,6,7])
xr1

array([5, 6, 7])

In [16]:
xr1.ndim

1

In [17]:
XR1 = np.array([[5,6,7]])
XR1

array([[5, 6, 7]])

In [18]:
XR1.ndim

2

In [19]:
X1 = np.array([[5], [6]])
X1

array([[5],
       [6]])

In [20]:
X1.ndim

2

In [21]:
a = np.array([12,3,4])

In [22]:
b = np.array([[12,3,4]])

In [23]:
a.ndim # 괄호 겹수에 따라서 달라짐

1

In [24]:
b.ndim

2

In [25]:
X.ndim

2

In [26]:
X.dtype

dtype('int32')

In [27]:
type(X)

numpy.ndarray

In [28]:
X = np.array([[1],[2],[3]])

In [29]:
X

array([[1],
       [2],
       [3]])

In [30]:
X.shape

(3, 1)

In [31]:
X = np.array([[1., 2., 3.], 
              [4., 5., 6.,]])
X

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
X.shape

(2, 3)

In [33]:
X.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [34]:
X.reshape(3, 2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [35]:
X.reshape(1, 6)

array([[1., 2., 3., 4., 5., 6.]])

In [36]:
X.reshape(1, -1)

array([[1., 2., 3., 4., 5., 6.]])

In [37]:
X.reshape(6, 1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [38]:
X.reshape(-1, 1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [40]:
A = X.reshape(6, 1)
A

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [39]:
X

array([[1., 2., 3.],
       [4., 5., 6.]])

In [41]:
a = np.array([1,2,3])

In [42]:
a.T

array([1, 2, 3])

In [43]:
b = np.array([[1,2,3]])

In [44]:
b.T

array([[1],
       [2],
       [3]])

In [61]:
x1 = np.array([[5], [6], [8]])
x2 = np.array([[6], [7], [5]])
print('x1 = ', x1)
print('x2 = ', x2)

x1 =  [[5]
 [6]
 [8]]
x2 =  [[6]
 [7]
 [5]]


In [62]:
x2.shape

(3, 1)

In [63]:
x1T = x1.T
x2T = x2.T
print('x1T = ', x1T)
print('x2T = ', x2T)

x1T =  [[5 6 8]]
x2T =  [[6 7 5]]


In [64]:
x1TT = x1.reshape(1, 3)
x2TT = x2.reshape(1, 3)
print('x1TT = ', x1TT)
print('x2TT = ', x2TT)

x1TT =  [[5 6 8]]
x2TT =  [[6 7 5]]


* `vstack` (vertical (수직) stack (쌓다))

In [65]:
X = np.vstack([x1T, x2T])
X

array([[5, 6, 8],
       [6, 7, 5]])

* `hstack` (vertical (수평) stack (쌓다))

In [66]:
Xhstack = np.hstack([x1T, x2T])
Xhstack

array([[5, 6, 8, 6, 7, 5]])

In [70]:
Xhstack2 = np.hstack([x1, x2])
Xhstack2

array([[5, 6],
       [6, 7],
       [8, 5]])

In [78]:
onevec = np.ones((2, 3)) # 차원을 튜플로 1차원 이상인 경우
onevec

array([[1., 1., 1.],
       [1., 1., 1.]])

In [82]:
zerovec = np.zeros((2, 3)) # 차원을 튜플로 1차원 이상인 경우
zerovec

array([[0., 0., 0.],
       [0., 0., 0.]])

In [86]:
np.arange(0, 10) # 이상, 미만

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
for i in np.arange(3):
    print(i)

0
1
2


In [88]:
np.linspace(0, 3, 10) # 0부터 3까지인데 10개로 동일하게 만들어라

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [93]:
d = 2*np.random.rand(1, 10)-1
d

array([[ 0.38487487, -0.07288008,  0.80651579,  0.70343276, -0.77464815,
         0.87754757,  0.95561031, -0.59994147, -0.66243305,  0.23119063]])

In [94]:
e = np.random.randn(3, 4)
e

array([[-1.54810361,  2.09007728,  1.73043782, -0.09473139],
       [ 1.26636536,  1.0562518 , -0.5685202 ,  0.65324249],
       [-0.17528393,  0.18047252, -1.13344159,  0.20730094]])