## Numpy practice

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3]) # row 형태이 만들어짐
a

array([1, 2, 3])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(3,)

In [5]:
A = [1, 'b', 'c']

In [6]:
B = [10, 20, 30, 40, 50, 60] # 0 1 2 3 4 5 인덱스

In [7]:
B[3:6] # 인덱스 3번째부터 6번 전까지 40, 50, 60이 출력

[40, 50, 60]

In [8]:
Blist = B[3:6] # B에서 인덱스 3번째부터 6번째 전까지를 Blist에 저장
Blist

[40, 50, 60]

In [9]:
Blist[1] # Blist에서 1번째 인덱스에 있는 것을 가져옴
# 다르게 말하면 Blist = B[3:6]이므로 B[4]값과 같음 
# B[3] = 0번째 인덱스, B[4] = 1번째 인덱스, B[5] = 2번째 인덱스

50

In [10]:
B[4]

50

In [11]:
type(B[3:6])

list

## List in List

In [12]:
B = [1, 2, 'c', [1, 3, 4]]
B

[1, 2, 'c', [1, 3, 4]]

In [13]:
B[3] # B에서 3번째 인덱스 값
# B[0] = 1, B[1] = 2, B[2] = 'c', B[3] = [1, 3, 4]

[1, 3, 4]

In [14]:
B[3][1] # B의 3번째 인덱스에서 1번째 인덱스
# B[3] = [1, 3, 4]
# B[3][0] = [1], B[3][1] = [3], B[3][2] = [4]

3

In [15]:
type(B[3])

list

In [16]:
C = [[1,2,3,4], [3, [12, 4, 5, 65], 'c', 10], 'a']
C

[[1, 2, 3, 4], [3, [12, 4, 5, 65], 'c', 10], 'a']

In [17]:
C[1]
# C[0] = [1,2,3,4], C[1] = [3, [12,4,5,65], 'c', 10], C[2] = 'a'

[3, [12, 4, 5, 65], 'c', 10]

In [18]:
C[1][1]
# C[1][0] = 3, C[1][1] = [12,4,5,65], C[1][2] = 'c', C[1][3] = 10,

[12, 4, 5, 65]

In [19]:
C[1][1][3]
#C[1][1][0] = 12, C[1][1][1] = 4, C[1][1][2] = 5, C[1][1][3] = 65

65

In [20]:
C[1][1][3] + 10

75

## Vector의 표기 단위 차이

In [21]:
X = np.array([[5, 6, 8], [6, 7, 4]])
X

array([[5, 6, 8],
       [6, 7, 4]])

In [22]:
X.ndim

2

In [23]:
X.dtype # dtype을 통해서 어떤 데이터 형태인지 알 수 있음

dtype('int32')

In [24]:
type(X) # numpy의 array임을 알 수 있음

numpy.ndarray

In [25]:
xr1 = np.array([5, 6, 7]) # row가 기준
xr1

array([5, 6, 7])

In [26]:
xr1.ndim # 차원의 수를 알 수 있음, 대괄호의 갯수를 세면 알 수 있음

1

In [27]:
XR1 = np.array([[5, 6, 7]])
XR1

array([[5, 6, 7]])

In [28]:
XR1.ndim

2

In [29]:
X1 = np.array([[5], [6]]) # column vector로 보기 위해선 2차원으로
X1

array([[5],
       [6]])

In [30]:
X1.ndim

2

In [31]:
a = np.array([12, 3, 4])

In [32]:
b = np.array([[12, 3, 4]])

In [33]:
a.ndim

1

In [34]:
b.ndim

2

In [35]:
X = np.array([[1], [2], [3]])
X

array([[1],
       [2],
       [3]])

In [36]:
X.shape

(3, 1)

In [37]:
X = np.array([[1., 2., 3.],
             [4., 5., 6.,]])
X

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
X.shape # X의 행렬이 column : 2, row : 3 임

(2, 3)

In [39]:
X.T # 행렬 X를 전치 전치는 대각선을 기준으로 뒤집음

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [40]:
X.reshape(3, 2) # 행렬이 column : 2, row : 3에서 colunm : 3, row : 2로 바뀜을 알 수 있음
# reshape은 행렬의 형태를 바꾸어줌

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [41]:
X.reshape(1, 6) # column : 1, row : 6

array([[1., 2., 3., 4., 5., 6.]])

In [42]:
X.reshape(1, -1) # 위에와 결과가 같은 것으로 보아 -1의 역할은 차원을 자동으로 맞추어줌

array([[1., 2., 3., 4., 5., 6.]])

In [43]:
A = X.reshape(6, 1)
A

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [44]:
X # 위에 바꾼 shape을 보존하려면 다른 변수에 저장을 해야된다.

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [46]:
a.T

array([1, 2, 3])

In [47]:
a.T.ndim

1

In [48]:
b = np.array([[1,2,3]])
b

array([[1, 2, 3]])

In [49]:
b.T # 위의 전치에서는 변하지 않는데 아래의 전치에서는 변함을 볼 수 있음
# 그 이유는 위의 a는 1차원이고, 아래의 b는 2차원임을 알 수 있음
# 교수님이 주의 해야된다고 영상에서 말씀해주심

array([[1],
       [2],
       [3]])

In [50]:
b.T.ndim

2

In [51]:
x1 = np.array([[5], [6], [8]])
x2 = np.array([[6], [7], [5]])
print('x1 = ', x1)
print('x2 = ', x2)

x1 =  [[5]
 [6]
 [8]]
x2 =  [[6]
 [7]
 [5]]


In [52]:
x1.shape

(3, 1)

In [53]:
x2.shape

(3, 1)

In [54]:
x1T = x1.T
x2T = x2.T
print('x1T = ', x1T)
print('x2T = ', x2T)

x1T =  [[5 6 8]]
x2T =  [[6 7 5]]


In [55]:
x1TT = x1.reshape(1, 3) # reshape을 통해서 column 3, row 1을 column 1, row 3으로 바꿔줌
x2TT = x2.reshape(1, 3)
print('x1TT = ', x1TT)
print('x2TT = ', x2TT)

# 위에 전치 시킨거랑 결과가 같음을 알 수 있음

x1TT =  [[5 6 8]]
x2TT =  [[6 7 5]]


In [56]:
X = np.vstack([x1T, x2T]) # vstack : 수직으로 쌓음
X

array([[5, 6, 8],
       [6, 7, 5]])

In [57]:
Xhstack = np.hstack([x1T, x2T]) # hstack : 수평으로 쌓음
Xhstack

array([[5, 6, 8, 6, 7, 5]])

In [58]:
Xhstack2 = np.hstack([x1, x2]) # hstack : 수평으로 쌓음
Xhstack2

array([[5, 6],
       [6, 7],
       [8, 5]])

In [59]:
onevec = np.ones((2, 3)) # 1로 채워진 column 2, row 3의 형태의 행렬을 만듦
onevec

# 주의 : 튜플 형태로 들어가야된다.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
zerovec = np.zeros((3, 3)) # 0으로 채워진 column 3, row 3의 형태의 행렬을 만듦
zerovec

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.arange(0, 10) # 0이상, 10미만

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
for i in np.arange(3):
    print(i)

0
1
2


In [63]:
np.linspace(0, 5, 20) # 0부터 5까지 20개로 일정하게 나누는 것을 볼 수 있음

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [64]:
d = np.random.randn(1, 10)
d

# 평균 0, 표준편차 1의 가우시안 정규분포

array([[-0.18177772, -1.19380457,  0.49684363,  0.4259922 , -0.1406862 ,
        -0.59549454, -0.17057691,  1.25722032, -2.41686656,  0.60918795]])

In [65]:
d1 = 2*np.random.randn(1, 10)
d1

array([[ 1.98208621, -4.68514829,  1.92166064, -1.71161245,  0.09021027,
        -3.4509672 , -3.38319638,  0.64904326, -1.29308369, -0.42825636]])

In [66]:
d2 = 2*np.random.randn(1, 10) - 2
d2

array([[-1.16141967, -2.43566644, -3.84526889, -2.80834101, -0.72951184,
         1.8613768 , -4.19721403, -1.28863086, -4.98491979, -0.03037973]])

In [67]:
e = np.random.randn(3, 4) # column 3, row 4 짜리 행렬
e

array([[ 1.43759715, -0.15230799, -0.32679422,  1.29508715],
       [ 1.42598196, -0.66820649,  1.03584279, -0.39686024],
       [-0.66925359,  0.4114331 , -2.01318983,  0.12470125]])

## squeeze() : 차원축소

In [68]:
f = np.array([[[1,2,3,4]]])
f

array([[[1, 2, 3, 4]]])

In [69]:
f.ndim

3

In [70]:
f.shape

(1, 1, 4)

In [71]:
f.squeeze() # 위에서 보면 차원이 3치원임을 알 수 있음, squeeze를 통해서 차원을 축소함

array([1, 2, 3, 4])

In [72]:
f.squeeze().ndim

1

In [73]:
f.squeeze().shape

(4,)

## Matrix multiplication

In [74]:
A = np.arange(0, 6) # 0부터 6미만까지 0 1 2 3 4 5 column 1, row 6
A

array([0, 1, 2, 3, 4, 5])

In [75]:
A = np.arange(0, 6).reshape(3, 2) # column 3, row 2
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [76]:
A.shape

(3, 2)

In [77]:
B = np.random.randn(3, 4)
B

array([[ 2.6423238 ,  0.02362909, -0.99881005,  0.40071092],
       [ 0.33731274,  1.46532794, -0.46240933, -0.51013436],
       [-0.69942378, -0.49781885,  0.98773484,  0.40664097]])

In [78]:
B.shape

(3, 4)

In [79]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [80]:
A[0,1]

1

In [81]:
A[0][1]
# 위에 와 같은 결과임을 볼 수 있음

1

In [82]:
A[2, 1]

5

In [83]:
a1 = A[:, 0] # 첫 column의 모든 것을 가져옴
a1

array([0, 2, 4])

In [84]:
a1.ndim # 1차원임을 볼 수 있음

1

In [85]:
a2 = A[:, 0].reshape(-1, 1) # reshape에서 -1을 통해서 맞는 차원을 잡아줌
a2

array([[0],
       [2],
       [4]])

In [86]:
a2.ndim # column vector로 만들기 위해서 차원이 2로 바뀜

2

In [87]:
B

array([[ 2.6423238 ,  0.02362909, -0.99881005,  0.40071092],
       [ 0.33731274,  1.46532794, -0.46240933, -0.51013436],
       [-0.69942378, -0.49781885,  0.98773484,  0.40664097]])

In [88]:
b2 = B[:, 1].reshape(-1, 1)
b2

array([[ 0.02362909],
       [ 1.46532794],
       [-0.49781885]])

In [90]:
C = np.matmul(a1.T, b2)
print(C)

[0.93938047]


In [91]:
C.shape

(1,)

In [92]:
a = np.linspace(0, 6, 4) # 0부터 6까지 4개로 나눠라
a

array([0., 2., 4., 6.])

In [95]:
a = np.linspace(0, 6, 4).reshape(1, 4)
a

array([[0., 2., 4., 6.]])

In [96]:
b = np.ones((4, 1)) # 항상 주의 : 튜플 형태로 넣기
b

array([[1.],
       [1.],
       [1.],
       [1.]])

In [97]:
np.matmul(a, b)

array([[12.]])

In [98]:
np.matmul(a, b)[0]

array([12.])

In [99]:
np.matmul(a, b)[0][0]

12.0

In [100]:
D = np.random.randn(3, 3)
D

array([[ 0.40650095, -0.33816965, -0.66709436],
       [ 0.94080731,  0.14555945,  0.25575788],
       [ 1.09022962,  0.71960643,  1.3977588 ]])

In [101]:
E = np.random.randn(3, 3)
E

array([[-0.94112792,  1.13522862,  0.22568251],
       [ 1.65389035,  0.14220253, -2.36050334],
       [ 0.33007444, -0.39869122, -1.54702849]])

In [102]:
D + E

array([[-0.53462697,  0.79705897, -0.44141185],
       [ 2.59469766,  0.28776199, -2.10474546],
       [ 1.42030407,  0.32091521, -0.14926969]])

In [103]:
D - E

array([[ 1.34762887, -1.47339828, -0.89277688],
       [-0.71308304,  0.00335692,  2.61626121],
       [ 0.76015518,  1.11829765,  2.94478729]])

In [104]:
d1 = D[0,:]
e1 = E[0,:]

In [105]:
d1 + e1

array([-0.53462697,  0.79705897, -0.44141185])

In [106]:
a = np.array([1,2,3,4])
b = 2*np.ones(4)
b

array([2., 2., 2., 2.])

In [107]:
a

array([1, 2, 3, 4])

In [108]:
c = a * b # 행렬곱이 일어나지 않음 행렬곱은 matmul, *과 matmul과는 다른 연산
c

array([2., 4., 6., 8.])

In [109]:
np.sum(a*b)

20.0

In [112]:
a

array([1, 2, 3, 4])

In [111]:
b.reshape(-1, 1)

array([[2.],
       [2.],
       [2.],
       [2.]])

In [110]:
np.matmul(a, b.reshape(-1, 1)) # 행렬곱 연산이 이루어짐

array([20.])

In [113]:
A = np.arange(3, 11, 1) # 3부터 11미만까지 1개씩 출력
A

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
A = np.arange(3, 11, 1).reshape(2, 4)
A

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [115]:
np.sum(A)

52

In [116]:
np.sum(A, axis = 0) # 수직으로 더 함

array([10, 12, 14, 16])

In [117]:
np.sum(A, axis = 1) # 수평으로 더 함

array([18, 34])

In [119]:
c = np.sum(A, axis = 1).reshape(-1, 1) # column 형태는 2차원으로 바뀜
c

array([[18],
       [34]])

In [121]:
c.ndim

2

# Broadcast

In [122]:
A = np.random.randn(4, 3)
A

array([[-1.26982738,  2.42239211, -0.53197578],
       [-1.1690696 ,  1.98750253,  1.25228823],
       [-0.56373033, -0.76948337,  0.17375939],
       [-0.56896138,  0.66356666, -0.86707885]])

In [123]:
B = np.ones((4, 1))
B

array([[1.],
       [1.],
       [1.],
       [1.]])

In [124]:
A + B

array([[-0.26982738,  3.42239211,  0.46802422],
       [-0.1690696 ,  2.98750253,  2.25228823],
       [ 0.43626967,  0.23051663,  1.17375939],
       [ 0.43103862,  1.66356666,  0.13292115]])