In [24]:
import numpy as np
import torch

* 강의를 위해서 임의의 dataset을 준비함 예제로 보면 된다.
* Data는 장미과와 국화과의 A효소, B효소, C효소, D효소를 측정한 값이라고 가정
* Label은 각 sample이 장미인지(0) 국화인지(1)에 대한 정보라고 가정

In [25]:
batch_size = 10 # 꽃의 수
num_feature = 4 # A B C D
torch.manual_seed(0)

X_batch = torch.randn(batch_size, num_feature)
Y_batch = (torch.sum(X_batch, dim=1)>0).type(torch.float).reshape(-1, 1)

In [26]:
X_batch # row는 첫 번째 꽃에 대한 ABCD 효소

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473],
        [-1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530],
        [-0.2159, -0.7425,  0.5627,  0.2596],
        [-0.1740, -0.6787,  0.9383,  0.4889],
        [ 1.2032,  0.0845, -1.2001, -0.0048],
        [-0.5181, -0.3067, -1.5810,  1.7066]])

In [27]:
Y_batch

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.]])

## single neuron

In [28]:
W = torch.randn(num_feature, 1) # 입력 크기, 출력 크기
b = 1
Z = torch.matmul(X_batch, W) + b
print(Z)

tensor([[ 2.2910],
        [ 3.0975],
        [ 1.6780],
        [ 1.0120],
        [ 1.4991],
        [-0.5044],
        [ 1.4891],
        [ 1.3363],
        [ 0.2980],
        [-1.8288]])


In [29]:
z_loop = torch.empty(batch_size, 1)
for i in torch.arange(batch_size):
    z_loop[i,:] = torch.matmul(W.T, X_batch[i,:].T) + b # 뒤에 X_batch는 전치를 왜 함? 안 해도 값이 같음
print(z_loop)

tensor([[ 2.2910],
        [ 3.0975],
        [ 1.6780],
        [ 1.0120],
        [ 1.4991],
        [-0.5044],
        [ 1.4891],
        [ 1.3363],
        [ 0.2980],
        [-1.8288]])


C:\Users\OH\AppData\Local\Temp\ipykernel_11020\2857332262.py:3: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2985.)
  z_loop[i,:] = torch.matmul(W.T, X_batch[i,:].T) + b # 뒤에 X_batch는 전치를 왜 함? 안 해도 값이 같음


In [30]:
def ReLU(Z):
    Z = torch.clamp(Z, min = 0)
    return Z
    
A = ReLU(Z)
print(A)

tensor([[2.2910],
        [3.0975],
        [1.6780],
        [1.0120],
        [1.4991],
        [0.0000],
        [1.4891],
        [1.3363],
        [0.2980],
        [0.0000]])


## Single Layer Network

* 한개의 Layer에 K = 5개의 neuron이 있는 network를 구성하고 출력을 구하세요
* Activation function은 모든 neuron에 ReLU를 적용
* 모든 weight는 Gaussian 분포를 랜덤으로 생성 torch.randn()
* i 번째 neuron의 weight들을 W_i라고 할 때
* W = [W_1, W_2, W_3, W_4, W_5]라고 하고, weight matrix W를 만드세요
* W = torch.randn(??, ??)로 생성
* Bias 역시 b라는 tensor에 저장하고, 각 neuron 별로 1로 설정
* b = torch.ones(??, ??)
* 아래 problem 2-2에서 수업에서 배운 Z 행렬과 A 행렬을 구하세요

## problem 2-1

* Z 행렬과 A 행렬의 차원은 어떻게 나오는지

In [31]:
# 답 : Z = np.randn(B = 10, 5), A = np.randn(B = 10, 5)

## problem 2-2

In [32]:
torch.manual_seed(0)

X = torch.randn(batch_size, num_feature)
W = torch.randn(num_feature, 5)
b = torch.ones((batch_size, 5))
Z = np.matmul(X_batch, W) + b
A = ReLU(Z)
XW = np.matmul(X, W)

print('X = ', X)
print('W = ', W)
print('b = ', b)
print('Z = ', Z)
print('A = ', A)
print('XW = ', XW)
print('X.shape = ', X.shape)
print('W.shape = ', W.shape)
print('b.shape = ', b.shape)
print('Z.shape = ', Z.shape)
print('A.shape = ', A.shape)
print('WX.shape = ', XW.shape)

X =  tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473],
        [-1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530],
        [-0.2159, -0.7425,  0.5627,  0.2596],
        [-0.1740, -0.6787,  0.9383,  0.4889],
        [ 1.2032,  0.0845, -1.2001, -0.0048],
        [-0.5181, -0.3067, -1.5810,  1.7066]])
W =  tensor([[ 2.0553e-01, -4.5033e-01, -5.7308e-01, -5.5536e-01, -1.1256e+00],
        [-3.1700e-01, -1.0925e+00, -8.5194e-02, -9.3348e-02,  6.8705e-01],
        [-8.3832e-01,  8.9182e-04, -7.5043e-01,  1.8541e-01,  6.2114e-01],
        [ 6.3818e-01, -2.4600e-01,  2.3025e+00, -1.8817e+00, -4.9727e-02]])
b =  tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 

## problem 3
* x(3)를 입력으로하는 2번째 neuron의 결과값을 출력하세요
* 위에서 구한 Z[i, j] 인덱싱을 통해서 출력하세요
* python의 인덱싱은 0부터 시작한다는 것을 주의하세요

In [33]:
X[2].shape

torch.Size([4])

In [34]:
X

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473],
        [-1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530],
        [-0.2159, -0.7425,  0.5627,  0.2596],
        [-0.1740, -0.6787,  0.9383,  0.4889],
        [ 1.2032,  0.0845, -1.2001, -0.0048],
        [-0.5181, -0.3067, -1.5810,  1.7066]])

In [35]:
X[2]

tensor([ 0.3223, -1.2633,  0.3500,  0.3081])

In [36]:
W[:,]

tensor([[ 2.0553e-01, -4.5033e-01, -5.7308e-01, -5.5536e-01, -1.1256e+00],
        [-3.1700e-01, -1.0925e+00, -8.5194e-02, -9.3348e-02,  6.8705e-01],
        [-8.3832e-01,  8.9182e-04, -7.5043e-01,  1.8541e-01,  6.2114e-01],
        [ 6.3818e-01, -2.4600e-01,  2.3025e+00, -1.8817e+00, -4.9727e-02]])

In [37]:
W[:,1].reshape(-1, 1)

tensor([[-4.5033e-01],
        [-1.0925e+00],
        [ 8.9182e-04],
        [-2.4600e-01]])

In [38]:
b[2].shape

torch.Size([5])

In [39]:
Z = np.matmul(X[2], W[:,]) + b[2]
# Z
A = ReLU(Z)
A

tensor([1.3700, 2.1595, 1.3698, 0.4240, 0.0000])

In [40]:
print('answer =', A[1])

answer = tensor(2.1595)


## problem 4: Multi-Layer network
* 3개의 layer가 있는 network를 구성
* 2번째 layer의 입력 크기는 k[1] = 16, 출력 크기는 k[2] = 6
* 마지막 layer의 출력은 k[3] = 1개의 neuron으로 구성
* 각 layer의 연산값을 구하시오
    * 각 layer의 선형 변환 결과값은 Z1, Z2, Z3로 저장
    * 각 layer의 결과값은 A1, A2, A3로 저장
* 모든 weight는 Gaussian 랜덤 변수로 생성, bias는 1로 구성된 벡터로 생성
* 각 layer의 weight는 W1, W2, W3로 하고, bias는 b1, b2, b3로 생성
* Activation 함수는 ReLU를 적용
* Loop 없이 행렬연산으로 구성

In [48]:
W1 = torch.randn(num_feature, 16)
W2 = torch.randn(16, 6)
W3 = torch.randn(6, 1)

b1 = torch.ones((batch_size, 16))
b2 = torch.ones((batch_size, 6))
b3 = torch.ones((batch_size, 1))

Z1 = torch.matmul(X_batch, W1) + b1
A1 = ReLU(Z1)
Z2 = torch.matmul(A1, W2) + b2
A2 = ReLU(Z2)
Z3 = torch.matmul(A2, W3) + b3
A3 = ReLU(Z3)

In [49]:
print(Z1.shape)
print(Z1)

torch.Size([10, 16])
tensor([[ 1.3895,  2.7307,  0.4425,  1.5148, -0.5831,  2.6471,  2.2709,  1.7535,
          0.2448,  1.5904, -0.7494,  3.0297,  3.6558, -0.5646,  0.5738,  0.1979],
        [ 5.1927,  1.5904, -0.8478,  5.3809,  1.4204, -1.9857, -1.1945,  3.7331,
          2.9422,  1.1654,  0.3122,  1.3705,  1.0481,  2.7797,  4.6984,  2.2839],
        [ 1.6287,  1.3993,  0.7631,  2.1163,  2.6092,  3.9219,  1.9780, -0.5877,
         -0.4297,  0.7422,  0.7852,  3.0681,  1.6857,  1.2953,  0.0256, -0.8328],
        [-1.3477,  0.7864, -0.5992,  0.0969, -0.0293, -3.3191,  0.6593,  0.4956,
          0.8589,  1.5405,  0.5275, -2.1166, -1.1360,  1.9938,  2.5719,  3.4393],
        [-1.5183,  2.5148,  0.6834, -0.6490, -0.3412,  4.0840,  3.8433, -0.8106,
         -1.6353,  1.5724, -0.6586,  2.6544,  3.1000, -0.9549, -1.3304, -0.4940],
        [ 1.1630, -0.1191,  3.5546,  0.1057,  4.2038,  7.3419,  2.2010, -1.7828,
         -0.4161, -0.2162,  2.9292,  3.6366,  1.3462,  0.6885, -2.6723, -2.6269],
 

In [50]:
print(Z2.shape)
print(Z2)

torch.Size([10, 6])
tensor([[  1.9137,  -1.0062,   2.3766,   6.1688,  -8.5389,   4.9134],
        [-13.9765,  -2.4794,  -4.6007,  11.3645, -14.5665,  -7.4800],
        [  7.8733,  -7.0355,  -1.1037,  -3.3914,  -2.9546,   1.7027],
        [ -6.5202,  -3.6515,  -4.9261,   4.7627,  -2.3993,  -1.0504],
        [  7.1427,  -1.5242,   4.5426,   0.4195,  -4.1756,   8.2852],
        [ 25.5169,  -9.5745,   0.3278,  -5.6337,   1.1771,   5.1426],
        [  3.0988,  -4.3540,  -0.2907,  -1.1413,  -1.3359,   1.8877],
        [  3.7680,  -5.6240,   0.3110,  -1.0453,  -0.8318,   1.1303],
        [ 14.4201,  -2.8338,  -2.8916,   2.4184, -11.2742,  -5.7170],
        [ 23.7240,   1.3002,   2.4048,   1.1020,  -3.9789,   3.0966]])


In [51]:
print(Z3.shape)
print(Z3)

torch.Size([10, 1])
tensor([[ 8.3970],
        [ 7.4530],
        [ 8.3471],
        [ 3.7044],
        [10.9065],
        [23.7129],
        [ 4.5640],
        [ 4.6411],
        [14.1077],
        [22.1548]])


In [52]:
print(A3.shape)
print(A3)

torch.Size([10, 1])
tensor([[ 8.3970],
        [ 7.4530],
        [ 8.3471],
        [ 3.7044],
        [10.9065],
        [23.7129],
        [ 4.5640],
        [ 4.6411],
        [14.1077],
        [22.1548]])


## problem 5
* 위에서 구한 A3[i,j]의 인덱싱을 통해서 h(x(3))을 출력
* 역시 python 인덱싱은 0부터 시작한다는 것을 주의

In [53]:
print('h_theta(x3) = ', A3[3,:])

h_theta(x3) =  tensor([3.7044])


## problem 6
* 위에서 공부한 것을 함수로 만들어 본다. 아래 한 layer의 선형 변환을 연산하는 class를 만들어보자
* Class는 my_linear_layer()
    * __init__(self, n_input_, n_output) 함수:
        * self.W 변수 초기화: Weight 행렬 self.W를 랜덤 Gaussian 생성(차원에 맞는)
        * self.b 변수 초기화: bias 행렬 self.b를 모두 1인 벡터 생성(차원에 맞는)
    * forward(A) 함수:
        * 입력: A는 sample batch X 또는 전 layer에서 들어오는 입력 batch A[L-1]을 입력하는 자리
        * return 값
            * Z 변수는 A[L-1]의 선형 변환 값, 즉 Z[L]

In [54]:
# class my_linear_layer():
#     def __init__(self, n_input, n_output):
#         self.n_input = n_input
#         self.n_output = n_output
        
#         self.W = []
#         self.b = []
        
#         for i in range(1, 5):
#             if i == 0:
#                 self.W.append(np.random.randn(n_input, 5))
#                 self.b.append(np.random.randn(10, 5))
            
#             elif i < 5:
#                 self.W[i].append(np.random.randn(4, n_output))
#                 self.b[i].append(np.random.randn(10, n_output))
                
#             else:
#                 self.W.append(np.random.randn(4, 5))
#                 self.W.append(np.random.randn(1, 5))
                
#     def forward(self, x):
#         self.Z = []
#         self.A = []
        
#         for i in range(1, 5):
#             if i < 5:
#                 self.Z = np.matmul(x, self.W[i]) + self.b[i]
#                 self.Z.append(self.Z)
#                 self.A = ReLU(self.Z)
#                 self.A.append(self.A)
    
#     # print(Z)
#     # print(A)
#         return Z

In [55]:
import numpy as np
import torch

In [56]:
batch_size = 10 # 꽃의 수
num_feature = 4 # A B C D
torch.manual_seed(0)

X_batch = torch.randn(batch_size, num_feature)
Y_batch = (torch.sum(X_batch, dim=1)>0).type(torch.float).reshape(-1, 1)

In [61]:
class my_linear_layer():
    def __init__(self, n_input, n_output):
        self.n_input = n_input
        self.n_output = n_output
        
        self.W = torch.randn(n_input, n_output)
        self.b = torch.ones((1, n_output))
        
    def forward(self, A):
        Z = np.matmul(A, self.W)
        return Z

In [62]:
mll = my_linear_layer(num_feature, 5) #인스턴스
mll.forward(X_batch)

tensor([[ 1.0259, -0.8468, -0.2874, -0.9014, -1.2395],
        [ 1.1053,  0.3770, -2.3077, -1.5116, -3.4858],
        [ 3.2555,  0.3657,  0.1774, -1.2346,  0.5884],
        [-3.7106, -0.0888, -1.0279,  0.3927,  2.2091],
        [ 0.6620, -0.8805,  0.6564, -0.5711,  1.8937],
        [ 4.5180,  0.8361,  2.4116,  0.1107,  1.2406],
        [ 0.7660, -0.1162, -0.0184, -0.6416,  1.2296],
        [ 0.2537, -0.0804,  0.0118, -0.5609,  2.2824],
        [ 3.2380,  1.0130,  0.7145,  0.1075, -2.5468],
        [ 0.5108, -0.0874,  2.9933,  2.2403, -0.6644]])

In [63]:
print(mll.W)
print(mll.b)

tensor([[ 1.9415,  0.7915, -0.0203, -0.4372, -0.2188],
        [-2.4351, -0.0729, -0.0340,  0.9625,  0.3492],
        [-0.9215, -0.0562, -0.6227, -0.4637,  1.9218],
        [-0.4025,  0.1239,  1.1648,  0.9234,  1.3873]])
tensor([[1., 1., 1., 1., 1.]])


## Building a Linear Layer with torch.nn
* 위에서 수행한 작업은 pytorch에서는 torch.nn.Linear라는 명령어로 쉽게 구현 가능

In [64]:
import torch.nn as nn
W = torch.randn(num_feature, 5)
L1 = nn.Linear(num_feature, 5)
Zll = L1(X_batch)
Zll

tensor([[ 0.2961,  0.7004, -0.8614,  0.2921, -0.5018],
        [-0.1483,  0.0637, -0.1383,  0.4197, -0.8470],
        [ 0.1854,  0.1652, -0.2639,  0.1737, -0.0945],
        [-0.0614,  0.6224, -0.4242,  0.1581, -0.1709],
        [ 0.3559,  0.9299, -1.0427,  0.2574,  0.0060],
        [ 0.6099, -0.5685,  0.6088, -0.6778, -0.0804],
        [ 0.1734,  0.4933, -0.5239,  0.1931, -0.1087],
        [ 0.1284,  0.5906, -0.5904,  0.2340,  0.0529],
        [ 0.4184, -0.8945,  0.9784, -0.6714, -0.7855],
        [ 0.9594, -0.6232,  0.8436, -1.3285, -0.7340]],
       grad_fn=<AddmmBackward0>)

In [ ]:
############### 강의에서의 숫자랑 다른데 ###############
############### 다시 해 보기 ###############
############### 우선 첫 번째 연습 ###############